export enum ModerationStatus {
  PENDING_CREATE = 'PENDING_CREATE',
  APPROVED = 'APPROVED',
  REJECTED_CREATE = 'REJECTED_CREATE',
  PENDING_UPDATE = 'PENDING_UPDATE',
  REJECTED_UPDATE = 'REJECTED_UPDATE',
  PENDING_DELETE = 'PENDING_DELETE',
  REJECTED_DELETE = 'REJECTED_DELETE',
}

export const PUBLIC_MODERATION_STATUSES = [
  ModerationStatus.PENDING_CREATE,
  ModerationStatus.APPROVED,
  ModerationStatus.PENDING_UPDATE,
  ModerationStatus.REJECTED_UPDATE,
  ModerationStatus.REJECTED_DELETE,
];
