export enum RouteRecommendationReason {
  NO_AVOIDANCE_REQUESTED = 'NO_AVOIDANCE_REQUESTED',
  NO_VALID_AVOIDED_ROUTE = 'NO_VALID_AVOIDED_ROUTE',
  NO_FULLY_COMPLIANT_ROUTE = 'NO_FULLY_COMPLIANT_ROUTE',
  AVOIDED_ROUTE_AUTO_APPLIED = 'AVOIDED_ROUTE_AUTO_APPLIED',
  AVOIDED_ROUTE_REQUIRES_CONFIRMATION = 'AVOIDED_ROUTE_REQUIRES_CONFIRMATION',
  PARTIAL_AVOIDED_ROUTE_REQUIRES_CONFIRMATION = 'PARTIAL_AVOIDED_ROUTE_REQUIRES_CONFIRMATION',
}
